### ISSUE TITLE
Uploading artifacts to S3 results in “The bucket you are attempting to access must be addressed using the specified endpoint”

### ISSUE THREAD

**Issue by jonburney** [travis-ci/artifacts#68]
_This is copied over from my SO question: http://stackoverflow.com/questions/35507396/travis-ci-uploading-artifacts-to-s3-results-in-the-bucket-you-are-attempting-t_

I have a [Travis CI ](https://travis-ci.org/jonburney/KingsgateMediaPlayer-Android/builds/110374129)build that is configured to upload the build artifacts to S3. I've followed the [Travis artifacts ](https://docs.travis-ci.com/user/uploading-artifacts/)documentation but when the build completes I get the following error (and the S3 container is empty).

> ERROR: failed to upload: /home/travis/build/jonburney/KingsgateMediaPlayer-Android/
> app/build/outputs/apk/app-release-unsigned.apk
>
> err: The bucket you are attempting to access must be addressed using the specified 
> endpoint. Please send all future requests to this endpoint.

I have tried to specify the "endpoint" option in the configuration but it was ignored. It appears to be attempting to upload the file to

https://s3.amazonaws.com/kmp-build-output/jonburney/KingsgateMediaPlayer-Android/30/30.1/app/build/outputs/apk/app-release-unsigned.apk.

Here is a copy of the relevant section from my .travis.yml file

```
addons:
    artifacts: true
    s3_region: "us-west-2"
    artifacts:
        paths:
          - $(git ls-files -o app/build/outputs | tr "\n" ":")
```

**Comment by brauliobo** [comment]
duplicate of https://github.com/travis-ci/artifacts/issues/57

**Comment by MariadeAnton** [comment]
@jonburney I believe this was fixed by replacing it to:

```
addons:
    artifacts:
        s3_region: "us-west-2"
        paths:
          - $(git ls-files -o app/build/outputs | tr "\n" ":")
```

Otherwise, please reopen or report at  #57 

Thanks for the help, @brauliobo!
